theme: jekyll-theme-cayman
title: Carbonic
plugins:
  - jekyll-seo-tag

webmaster_verifications:
  google: TEoM2-clv9NyZFINNVOiQPdGvn7Af7QASeVt29YFCzU

avatar: https://raw.githubusercontent.com/srevinsaju/carbonic/master/g960.png
footer-links:
  email: srevin03@gmail.com